name: Run Workflow from Specific Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow"
        required: true
        default: "dev"

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Execute Commands
        run: |
          echo "Running workflow on branch ${{ github.event.inputs.branch }}"
          # Add your specific commands here
